In [1]:
import numpy as np


In [2]:
array_n1=np.array([1,2,3])

In [3]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [4]:
array_n2=np.array([1,2,"3"],dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2.np.arange(start,stop,end)

In [5]:
print(np.arange(5))


[0 1 2 3 4]


In [6]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [7]:
arange=np.arange(1,10,2)
print(type(arange))

<class 'numpy.ndarray'>


# np.linspace(start,stop,num=x)

In [8]:
np_lin=np.linspace(0,1,10)
print(np_lin)
print(type(np_lin))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
<class 'numpy.ndarray'>


In [9]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [10]:
npz1=np.zeros(5)

# ndim for dimensions


In [11]:
npz1.ndim


1

In [13]:
npz2=np.zeros((5,5))
print(npz2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
npz2.ndim

2

In [15]:
npz3=np.zeros((5,5,5))
print(npz3)
npz3.ndim

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


3